### ISSUE TITLE
Cannot retrieve documents from Collections Data

### ISSUE THREAD

**Issue by enarltd** [Freddywhest/firestore-eloquent#15]
**Describe the bug**
I am trying to get all the documents from a Firestore collection. I am able to get the data and when I dd($results), I see the array of objects returned. But when I try to loop through the data or retrieve them to show in my blade view, I get nothing.

**To Reproduce**
$cData = Contribution::all();
dd($cData); //this give me the data from the collection

But I don't get anythig when I try this:
foreach ($cData as $value) {
dd(value); //looks like this does not run at all.
}

**Expected behavior**
The loop should run

**Comment by Freddywhest** [comment]
The documentation states that add ->data() to get the data.
Your have to be like 
foreach ($cData->data() as $value) {
dd(value); //looks like this does not run at all.
}

Or

$cData = Contribution::all()->data();

**Comment by enarltd** [comment]
I get this error when I do that...

See screenshot below:
<img width="1374" alt="Screenshot 2024-07-04 at 9 29 33 AM" src="https://github.com/Freddywhest/firestore-eloquent/assets/130680336/31464c89-ad2c-4f3a-99ff-39b2a92518a1">

**Comment by Freddywhest** [comment]
Do you want to count the data or display it

**Comment by Freddywhest** [comment]
If you want to do both, here an example:

`$cData = Contribution::all();`

`$count = $cData->count();`

`$data = $cData->data();
`

**Comment by enarltd** [comment]
I want to display it. There is no "count()" in my code. I want to get the documents and display them in my blade view.
The "->data()" works when I query using the "first()" or "find()" but when I am getting all(), it gives me that count() error.

**Comment by enarltd** [comment]
When I do this:
 $cData = Contribution::all();
  $contributionData = $cData->data();
  
  I still get the "count()" error on the 2nd line.

**Comment by Freddywhest** [comment]
I'm sure, look through your code

> Maybe I am ignorantly doing something wrong somewhere

**Comment by enarltd** [comment]
> I'm sure, look through your code
> 
> > Maybe I am ignorantly doing something wrong somewhere

Could you help with parts of the code I should check because I don't know where I am starting from though

**Comment by enarltd** [comment]
When I do dd($cData); I get the screeenshot below:

<img width="661" alt="Screenshot 2024-07-04 at 10 11 32 AM" src="https://github.com/Freddywhest/firestore-eloquent/assets/130680336/7e85dece-d617-49e8-8d00-bff6d08d6587">

But when I do dd($cData->data()); I get the error again.

**Comment by Freddywhest** [comment]
> > I'm sure, look through your code
> > > Maybe I am ignorantly doing something wrong somewhere
> 
> Could you help with parts of the code I should check because I don't know where I am starting from though

The error was related to the package, not your code. Sorry about that. Please update to the latest version (2.0.1)

**Comment by enarltd** [comment]
Thank you Sir
I'll revert soon

**Comment by enarltd** [comment]
> > Thank you Sir I'll revert soon
> 
> You're welcome! Please let me know after you have checked, so I can close the issue

Working perfectly Sir.
Thank you!
