### ISSUE TITLE
Returns an empty object when retrieving from firestore

### ISSUE THREAD

**Issue by alsong** [Freddywhest/firestore-eloquent#7]
**Describe the bug**
I am using an already existing firestore database. I created a document and it appeared in the collection. Now when i retrieve the
documents in the collection i get an array of empty objects, the fields do not show up although the number of objects is correct.

**To Reproduce**
I never changed the model file.
I just made
`$users = UserRoles::all();`

**Expected behavior**

**Screenshots**
![image](https://github.com/Freddywhest/firestore-eloquent/assets/19310511/daef3c86-1f1c-4351-bca8-08b8438ef802)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]

**Additional context**
The project is on laravel 10.

**Comment by Freddywhest** [comment]
Hello @alsong, Can you provide the code for UserRoles model

**Comment by alsong** [comment]
@Freddywhest 
`<?php

namespace App\FModels;

use Roddy\FirestoreEloquent\Facade\FModel;

class UserRoles extends FModel
{
    /**
    * Name of your firestore collection
    */
    protected $collection = 'customersData';

    /**
    * The primary key of the model/collection
    */
    protected $primaryKey = 'id';

    /**
    * The fillable property takes care of defining which fields are
    * to be considered when the user will insert or update data.
    * Fillable property should ba an array. e.g ['id', 'age', 'name']
    */
    protected $fillable = [];

    /**
    * The required property takes care of defining which fields
    * should be required and cannot be empty when inserting data only.
    * Required property should ba an array. e.g ['id', 'name']
    */
    protected $required = [];

    /**
    * The default property is use to set a default value for
    * the fields provided in the array if the fields is empty.
    * Default property should ba an array. e.g ['name' => 'Alfred', 'date' => date('Y-m-d)]
    */
    protected $default = [];

    /**
    * The fieldTypes property is use to set a types for
    * the fields provided in the array.
    * Supported types are: integer, string, array and object
    * fieldTypes property should ba an array. e.g ['name' => 'string', 'age' => 'int', 'date' => 'date']
    */
    protected $fieldTypes = [];
}
`

**Comment by alsong** [comment]
although when i do
$users = UserRoles::first();
echo $users returns an empty object but $users->name returns the name.

**Comment by Freddywhest** [comment]
dd() the users, if it also returns empty object

**Comment by alsong** [comment]
when you dd($users); its not empty. It actually shows logs
![image_2024-03-12_132848622](https://github.com/Freddywhest/firestore-eloquent/assets/19310511/0b787198-ee04-47bd-95d2-d15c916dd834)

**Comment by alsong** [comment]
@Freddywhest  i think i have found a work by for now.

` $users = UserRoles::first();
  return response()->json(['message' => 'Test complete', 'data' => $users->data()], 200);`
  
  so we add `data()` at the end and then it works

**Comment by Freddywhest** [comment]
The reason why you got an empty objects when using postman is because `UserRoles::all();` returns a php class but not an array that's why

**Comment by Freddywhest** [comment]
> @Freddywhest i think i have found a work by for now.
> 
> ` $users = UserRoles::first(); return response()->json(['message' => 'Test complete', 'data' => $users->data()], 200);`
> 
> so we add `data()` at the end and then it works

Oh that's great, I will add it to the documentation. Thanks

**Comment by alsong** [comment]
but now how do i resolve `UserRoles::all();` with postman because it will be used by many

**Comment by Freddywhest** [comment]
```
$roles = UserRoles::all();
    $array = [];
    foreach($roles as $r){
        array_push($array, $r->data());
    }
    return response()->json(['message' => 'Test complete', 'data' => $array], 200);
```

For the meantime, feel free to make use of this.  I'll be integrating support for array return in the API (Postman) with the next update.

**Comment by Freddywhest** [comment]
Let me know me it works

**Comment by alsong** [comment]
Yes it works ofcourse. Btw it will be showing some support for this project.

**Comment by Freddywhest** [comment]
> But please don't do this `$users->data()` it takes away the whole feel of using eloquent.

`->data()` is for API use only. When using it with Laravel there's no need to use `->data()`

**Comment by alsong** [comment]
> > But please don't do this `$users->data()` it takes away the whole feel of using eloquent.
> 
> That's true, `->data()` is for API use only. When using it with Laravel there's no need to use `->data()`

so me using inertiajs will not disturb me

**Comment by Freddywhest** [comment]
I have tried it with livewire but not with inertiajs.
I think inertia should be something like 
```
$users = User::first()
return Inertia::render('Users', [
            'user' => response()->json($users->data())
        ]);
```

OR
```
$users = Users::all();
    $array = [];
    foreach($users as $u){
        array_push($array, $u->data());
    }
    
    return Inertia::render('Users', [
            'users' => response()->json($array)
        ]);
```

**Comment by Freddywhest** [comment]
**Also try something like this and let me know if it works**
```
$user = User::first()
return Inertia::render('Users', [
            'user' => $user
        ]);
```

OR
```
$users = Users::all();
  
    return Inertia::render('Users', [
            'users' => $users
        ]);
```

**Comment by alsong** [comment]
this is funny but this is how pagination would work
` $roles = UserRoles::paginate(10);
        $array = [];
        foreach($roles->data() as $r){
            array_push($array, $r->data());
        }
        return response()->json(['message' => 'Test complete', 'data' => $array], 200);`

**Comment by Freddywhest** [comment]
> this is funny but this is how pagination would work ` $roles = UserRoles::paginate(10); $array = []; foreach($roles->data() as $r){ array_push($array, $r->data()); } return response()->json(['message' => 'Test complete', 'data' => $array], 200);`

That's simple, here's an example: 
```
$roles = UserRoles::paginate(10);
$pagination = $roles->pagination(); //It will provide the pagination info.
/**
result for $pagination
"pagination": {
        "total_pages": 8,
        "per_page": 1,
        "current_page": 1,
        "last_page": 8,
        "next_page": 2,
        "prev_page": null,
        "from": 0,
        "to": 1,
        "total": 8
    }
*/

$array = [];
foreach($roles->data() as $r){
    array_push($array, $r->data());
}
return response()->json(['message' => 'Test complete', 'data' => $array, "pagination" => $pagination], 200);
```

**Comment by alsong** [comment]
i think let me close the issue, you might have to update the docs.

**Comment by Freddywhest** [comment]
Sure, I'll include API documentation in the documentation for the upcoming update.
